--RACCOON 스키마
CREATE TABLE USER_TB
(
    USER_ID     VARCHAR2(40 BYTE),
    "PASSWORD"  VARCHAR2(200 BYTE),
    USER_NM     VARCHAR2(100 BYTE),
    CELNO       VARCHAR2(15 BYTE),
    ADDRESS1    VARCHAR2(600 BYTE),
    ADDRESS2    VARCHAR2(100 BYTE),
    USER_AUTH   CHAR(1 BYTE),
    INPT_DTTM   DATE,
    UPDT_DTTM   DATE
)

ALTER TABLE USER_TB ADD CONSTRAINT PK_USER_TB PRIMARY KEY(USER_ID);

ALTER TABLE USER_TB ADD NICKNAME VARCHAR2(30);

COMMENT ON TABLE USER_TB IS '유저 정보';
COMMENT ON COLUMN USER_TB.USER_ID IS 'ID';
COMMENT ON COLUMN USER_TB.PASSWORD IS '패스워드';
COMMENT ON COLUMN USER_TB.USER_NM IS '이름';
COMMENT ON COLUMN USER_TB.CELNO IS '연락처';
COMMENT ON COLUMN USER_TB.ADDRESS1 IS '주소';
COMMENT ON COLUMN USER_TB.ADDRESS2 IS '상세 주소';
COMMENT ON COLUMN USER_TB.USER_AUTH IS '사용자 구분';
COMMENT ON COLUMN USER_TB.INPT_DTTM IS '입력일';
COMMENT ON COLUMN USER_TB.NICKNAME IS '닉네임';

CREATE SEQUENCE VISIT_SEQ
MINVALUE 1
INCREMENT BY 1
START WITH 1
NOCACHE
NOORDER
NOCYCLE;

CREATE TABLE VISIT_TB(
	SEQ NUMBER PRIMARY KEY,
	SESSION_ID VARCHAR2(500),
	INPT_DTTM DATE,
	USER_IP VARCHAR2(30)
);


--코드

CREATE TABLE CODE_TB(
    CODE VARCHAR2(100) PRIMARY KEY,
    CODE_NM VARCHAR2(1000),
    UP_CODE VARCHAR2(100)
)
;

COMMENT ON TABLE CODE_TB IS '코드 테이블';
COMMENT ON COLUMN CODE_TB.CODE IS '코드';
COMMENT ON COLUMN CODE_TB.CODE_NM IS '코드명';
COMMENT ON COLUMN CODE_TB.UP_CODE IS '상위코드';
;

-- 게시글
CREATE TABLE SALESBOARD(
   ID NUMBER NOT NULL PRIMARY KEY,
   TITLE VARCHAR2(300),
   CONTENT CLOB,
   SALE_CATEGORY VARCHAR2(30),
   CELNO VARCHAR2(15),
   INPT_DTTM DATE,
   INPT_USER VARCHAR2(30),
   UPDT_DTTM DATE,
   UPDT_USER VARCHAR2(30),

   CONSTRAINT SALESBOARD_FK_USERID FOREIGN KEY(INPT_USER) REFERENCES USER_TB(USER_ID)
)
;

COMMENT ON TABLE SALESBOARD IS '판매게시판';
COMMENT ON COLUMN SALESBOARD.ID IS 'PK';
COMMENT ON COLUMN SALESBOARD.TITLE IS '제목';
COMMENT ON COLUMN SALESBOARD.CONTENT IS '내용';
COMMENT ON COLUMN SALESBOARD.SALE_CATEGORY IS '구매/판매여부';
COMMENT ON COLUMN SALESBOARD.CELNO IS '게시글 등록 연락처';
COMMENT ON COLUMN SALESBOARD.INPT_DTTM IS '등록일시';
COMMENT ON COLUMN SALESBOARD.INPT_USER IS '등록아이디';
COMMENT ON COLUMN SALESBOARD.UPDT_DTTM IS '수정일시';
COMMENT ON COLUMN SALESBOARD.UPDT_USER IS '수정아이디';
