CREATE TABLE USER_TB
(
    ID NUMBER,
    USER_ID     VARCHAR2(500 BYTE),
    "PASSWORD"  VARCHAR2(200 BYTE),
    USER_NM     VARCHAR2(100 BYTE),
    CELNO       VARCHAR2(15 BYTE),
    ADDRESS1    VARCHAR2(600 BYTE),
    ADDRESS2    VARCHAR2(100 BYTE),
    USER_AUTH   CHAR(1 BYTE),
    INPT_DTTM   DATE,
    UPDT_DTTM   DATE
)

ALTER TABLE USER_TB ADD CONSTRAINT PK_USER_TB PRIMARY KEY(ID);

ALTER TABLE USER_TB ADD NICKNAME VARCHAR2(30);
ALTER TABLE USER_TB ADD SIGNUP_DIV VARCHAR2(100);

COMMENT ON TABLE USER_TB IS '유저 정보';
COMMENT ON COLUMN USER_TB.USER_ID IS 'ID';
COMMENT ON COLUMN USER_TB.PASSWORD IS '패스워드';
COMMENT ON COLUMN USER_TB.USER_NM IS '이름';
COMMENT ON COLUMN USER_TB.CELNO IS '연락처';
COMMENT ON COLUMN USER_TB.ADDRESS1 IS '주소';
COMMENT ON COLUMN USER_TB.ADDRESS2 IS '상세 주소';
COMMENT ON COLUMN USER_TB.USER_AUTH IS '회원권한구분';
COMMENT ON COLUMN USER_TB.INPT_DTTM IS '입력일';
COMMENT ON COLUMN USER_TB.NICKNAME IS '닉네임';
COMMENT ON COLUMN USER_TB.SIGNUP_DIV IS '회원가입구분';

CREATE SEQUENCE USER_TB_SEQ; -- user_tb에 사용할 시퀀스
ALTER TABLE USER_TB MODIFY USER_ID VARCHAR2(500);