--CREATE TABLE USER_TB
--(
--    ID NUMBER,
--    USER_ID     VARCHAR2(500 BYTE),
--    "PASSWORD"  VARCHAR2(200 BYTE),
--    USER_NM     VARCHAR2(100 BYTE),
--    CELNO       VARCHAR2(15 BYTE),
--    ADDRESS1    VARCHAR2(600 BYTE),
--    ADDRESS2    VARCHAR2(100 BYTE),
--    USER_AUTH   CHAR(1 BYTE),
--    INPT_DTTM   DATE,
--    UPDT_DTTM   DATE
--)
--
--ALTER TABLE USER_TB ADD CONSTRAINT PK_USER_TB PRIMARY KEY(ID);
--
--ALTER TABLE USER_TB ADD NICKNAME VARCHAR2(30);
--ALTER TABLE USER_TB ADD SIGNUP_DIV VARCHAR2(100);
--
--COMMENT ON TABLE USER_TB IS '유저 정보';
--COMMENT ON COLUMN USER_TB.USER_ID IS 'ID';
--COMMENT ON COLUMN USER_TB.PASSWORD IS '패스워드';
--COMMENT ON COLUMN USER_TB.USER_NM IS '이름';
--COMMENT ON COLUMN USER_TB.CELNO IS '연락처';
--COMMENT ON COLUMN USER_TB.ADDRESS1 IS '주소';
--COMMENT ON COLUMN USER_TB.ADDRESS2 IS '상세 주소';
--COMMENT ON COLUMN USER_TB.USER_AUTH IS '회원권한구분';
--COMMENT ON COLUMN USER_TB.INPT_DTTM IS '입력일';
--COMMENT ON COLUMN USER_TB.NICKNAME IS '닉네임';
--COMMENT ON COLUMN USER_TB.SIGNUP_DIV IS '회원가입구분';
--
--CREATE SEQUENCE USER_TB_SEQ; -- user_tb에 사용할 시퀀스
--ALTER TABLE USER_TB MODIFY USER_ID VARCHAR2(500);

--MariaDB
CREATE TABLE USER_TB
(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'PK',
    USER_ID     VARCHAR(500) COMMENT 'ID',
    PASSWORD  VARCHAR(200) COMMENT '패스워드',
    USER_NM     VARCHAR(100) COMMENT '이름',
    CELNO       VARCHAR(15) COMMENT '연락처',
    ADDRESS1    VARCHAR(600) COMMENT '주소',
    ADDRESS2    VARCHAR(100) COMMENT '상세주소',
    USER_AUTH   CHAR(1) COMMENT '회원권한구분',
    INPT_DTTM   DATETIME COMMENT '입력일',
    UPDT_DTTM   DATETIME COMMENT '수정일',
    NICKNAME VARCHAR(30) COMMENT '닉네임',
    SIGNUP_DIV VARCHAR(100) COMMENT '회원가입구분'
    
) COMMENT '유저';

CREATE SEQUENCE USER_TB_SEQ; -- user_tb에 사용할 시퀀스

ALTER TABLE USER_TB ADD INPT_USER VARCHAR(100) COMMENT '등록유저명';
ALTER TABLE USER_TB ADD UPDT_USER VARCHAR(100) COMMENT '수정유저명';